name: Deploy Resume to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - resume.json

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}_node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}_node_modules-

      - name: Build Resume HTML
        run: |
          npm ci
          npm run setup
          npm run validate
          npm run export

      - name: Save build cache
        uses: actions/cache/save@v3
        with:
          path: build
          key: ${{ runner.OS }}_build-${{ hashFiles('resume.json') }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore build cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: build
          key: ${{ runner.OS }}_build-${{ hashFiles('resume.json') }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: steps.cache.outputs.cache-hit == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

      - name: Clear build cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh cache list
          gh cache delete ${{ runner.OS }}_build-${{ hashFiles('resume.json') }}

      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v4
